# Generated by Django 2.2.28 on 2023-01-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendadetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.DateField()),
                ('description', models.DateField()),
                ('assocatedname', models.DateField()),
                ('vendarid', models.DateField()),
            ],
        ),
    ]
